# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Zedboard/zedboard_master_XDC_RevC_D_v2.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD}]

# IP: bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0 || ORIG_REF_NAME==BD_clk_wiz_0}]

# IP: bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_0_0_0 || ORIG_REF_NAME==BD_cpu_0_0_0}]

# IP: bd/BD/ip/BD_kth_axi_rni_static_c1_0_0/BD_kth_axi_rni_static_c1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_axi_rni_static_c1_0_0 || ORIG_REF_NAME==BD_kth_axi_rni_static_c1_0_0}]

# IP: bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_gpio_0_0 || ORIG_REF_NAME==BD_axi_gpio_0_0}]

# IP: bd/BD/ip/BD_axi_timer_0_0/BD_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_0_0 || ORIG_REF_NAME==BD_axi_timer_0_0}]

# IP: bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_0 || ORIG_REF_NAME==BD_dlmb_v10_0}]

# IP: bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_0 || ORIG_REF_NAME==BD_ilmb_v10_0}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_0/BD_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_0}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_0/BD_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_0}]

# IP: bd/BD/ip/BD_lmb_bram_0/BD_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_0 || ORIG_REF_NAME==BD_lmb_bram_0}]

# IP: bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_mdm_1_0 || ORIG_REF_NAME==BD_mdm_1_0}]

# IP: bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rst_clk_wiz_50M_0 || ORIG_REF_NAME==BD_rst_clk_wiz_50M_0}]

# IP: bd/BD/ip/BD_cpu_0_0_axi_periph_0/BD_cpu_0_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_0_0_axi_periph_0 || ORIG_REF_NAME==BD_cpu_0_0_axi_periph_0}]

# IP: bd/BD/ip/BD_xbar_0/BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_0 || ORIG_REF_NAME==BD_xbar_0}]

# IP: bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_0_0 || ORIG_REF_NAME==BD_microblaze_0_0}]

# IP: bd/BD/ip/BD_kth_axi_rni_static_c1_0_1/BD_kth_axi_rni_static_c1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_axi_rni_static_c1_0_1 || ORIG_REF_NAME==BD_kth_axi_rni_static_c1_0_1}]

# IP: bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_pio_0_0_0 || ORIG_REF_NAME==BD_pio_0_0_0}]

# IP: bd/BD/ip/BD_axi_timer_1_0/BD_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_1_0 || ORIG_REF_NAME==BD_axi_timer_1_0}]

# IP: bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_1 || ORIG_REF_NAME==BD_dlmb_v10_1}]

# IP: bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_1 || ORIG_REF_NAME==BD_ilmb_v10_1}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_1/BD_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_1}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_1/BD_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_1}]

# IP: bd/BD/ip/BD_lmb_bram_1/BD_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_1 || ORIG_REF_NAME==BD_lmb_bram_1}]

# IP: bd/BD/ip/BD_cpu_0_1_axi_periph_0/BD_cpu_0_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_0_1_axi_periph_0 || ORIG_REF_NAME==BD_cpu_0_1_axi_periph_0}]

# IP: bd/BD/ip/BD_xbar_1/BD_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_1 || ORIG_REF_NAME==BD_xbar_1}]

# IP: bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_0_1_0 || ORIG_REF_NAME==BD_cpu_0_1_0}]

# IP: bd/BD/ip/BD_kth_axi_rni_static_c1_1_0/BD_kth_axi_rni_static_c1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_axi_rni_static_c1_1_0 || ORIG_REF_NAME==BD_kth_axi_rni_static_c1_1_0}]

# IP: bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_pio_0_1_0 || ORIG_REF_NAME==BD_pio_0_1_0}]

# IP: bd/BD/ip/BD_axi_timer_2_0/BD_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_2_0 || ORIG_REF_NAME==BD_axi_timer_2_0}]

# IP: bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_2 || ORIG_REF_NAME==BD_dlmb_v10_2}]

# IP: bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_2 || ORIG_REF_NAME==BD_ilmb_v10_2}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_2/BD_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_2}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_2/BD_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_2}]

# IP: bd/BD/ip/BD_lmb_bram_2/BD_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_2 || ORIG_REF_NAME==BD_lmb_bram_2}]

# IP: bd/BD/ip/BD_cpu_1_0_axi_periph_0/BD_cpu_1_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_1_0_axi_periph_0 || ORIG_REF_NAME==BD_cpu_1_0_axi_periph_0}]

# IP: bd/BD/ip/BD_xbar_2/BD_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_2 || ORIG_REF_NAME==BD_xbar_2}]

# IP: bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_pio_dpr_0 || ORIG_REF_NAME==BD_pio_dpr_0}]

# IP: bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_1_0_0 || ORIG_REF_NAME==BD_cpu_1_0_0}]

# IP: bd/BD/ip/BD_kth_axi_rni_static_c1_2_0/BD_kth_axi_rni_static_c1_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_axi_rni_static_c1_2_0 || ORIG_REF_NAME==BD_kth_axi_rni_static_c1_2_0}]

# IP: bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_pio_1_0_0 || ORIG_REF_NAME==BD_pio_1_0_0}]

# IP: bd/BD/ip/BD_axi_timer_3_0/BD_axi_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_3_0 || ORIG_REF_NAME==BD_axi_timer_3_0}]

# IP: bd/BD/ip/BD_dlmb_v10_3/BD_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_3 || ORIG_REF_NAME==BD_dlmb_v10_3}]

# IP: bd/BD/ip/BD_ilmb_v10_3/BD_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_3 || ORIG_REF_NAME==BD_ilmb_v10_3}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_3/BD_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_3}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_3/BD_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_3}]

# IP: bd/BD/ip/BD_lmb_bram_3/BD_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_3 || ORIG_REF_NAME==BD_lmb_bram_3}]

# IP: bd/BD/ip/BD_cpu_1_1_axi_periph_0/BD_cpu_1_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_cpu_1_1_axi_periph_0 || ORIG_REF_NAME==BD_cpu_1_1_axi_periph_0}]

# IP: bd/BD/ip/BD_xbar_3/BD_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_3 || ORIG_REF_NAME==BD_xbar_3}]

# IP: bd/BD/ip/BD_inverter_0/BD_inverter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_inverter_0 || ORIG_REF_NAME==BD_inverter_0}]

# IP: bd/BD/ip/BD_kth_2DNoC_2x2x1_c1_0_0/BD_kth_2DNoC_2x2x1_c1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_2DNoC_2x2x1_c1_0_0 || ORIG_REF_NAME==BD_kth_2DNoC_2x2x1_c1_0_0}]

# IP: bd/BD/ip/BD_xlconstant_0_0/BD_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xlconstant_0_0 || ORIG_REF_NAME==BD_xlconstant_0_0}]

# IP: bd/BD/ip/BD_Ground_1_0/BD_Ground_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_Ground_1_0 || ORIG_REF_NAME==BD_Ground_1_0}]

# IP: bd/BD/ip/BD_Ground_8_0/BD_Ground_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_Ground_8_0 || ORIG_REF_NAME==BD_Ground_8_0}]

# IP: bd/BD/ip/BD_Ground_15_0/BD_Ground_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_Ground_15_0 || ORIG_REF_NAME==BD_Ground_15_0}]

# XDC: bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0 || ORIG_REF_NAME==BD_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0 || ORIG_REF_NAME==BD_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0_ooc.xdc

# XDC: bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_cpu_0_0_0 || ORIG_REF_NAME==BD_cpu_0_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0_ooc_debug.xdc

# XDC: bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_axi_gpio_0_0 || ORIG_REF_NAME==BD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_axi_gpio_0_0 || ORIG_REF_NAME==BD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_axi_timer_0_0/BD_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_0_0 || ORIG_REF_NAME==BD_axi_timer_0_0}]

# XDC: bd/BD/ip/BD_axi_timer_0_0/BD_axi_timer_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_0 || ORIG_REF_NAME==BD_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_0 || ORIG_REF_NAME==BD_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_bram_if_cntlr_0/BD_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_bram_if_cntlr_0/BD_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/BD/ip/BD_lmb_bram_0/BD_lmb_bram_0_ooc.xdc

# XDC: bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_mdm_1_0 || ORIG_REF_NAME==BD_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0_ooc_trace.xdc

# XDC: bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rst_clk_wiz_50M_0 || ORIG_REF_NAME==BD_rst_clk_wiz_50M_0}]

# XDC: bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rst_clk_wiz_50M_0 || ORIG_REF_NAME==BD_rst_clk_wiz_50M_0}]

# XDC: bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0_ooc.xdc

# XDC: bd/BD/ip/BD_xbar_0/BD_xbar_0_ooc.xdc

# XDC: bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_microblaze_0_0 || ORIG_REF_NAME==BD_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0_ooc_debug.xdc

# XDC: bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_0_0_0 || ORIG_REF_NAME==BD_pio_0_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_0_0_0 || ORIG_REF_NAME==BD_pio_0_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_axi_timer_1_0/BD_axi_timer_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_1_0 || ORIG_REF_NAME==BD_axi_timer_1_0}]

# XDC: bd/BD/ip/BD_axi_timer_1_0/BD_axi_timer_1_0_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_1 || ORIG_REF_NAME==BD_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_1 || ORIG_REF_NAME==BD_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_bram_if_cntlr_1/BD_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_bram_if_cntlr_1/BD_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/BD/ip/BD_lmb_bram_1/BD_lmb_bram_1_ooc.xdc

# XDC: bd/BD/ip/BD_xbar_1/BD_xbar_1_ooc.xdc

# XDC: bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_cpu_0_1_0 || ORIG_REF_NAME==BD_cpu_0_1_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0_ooc_debug.xdc

# XDC: bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_0_1_0 || ORIG_REF_NAME==BD_pio_0_1_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_0_1_0 || ORIG_REF_NAME==BD_pio_0_1_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_axi_timer_2_0/BD_axi_timer_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_2_0 || ORIG_REF_NAME==BD_axi_timer_2_0}]

# XDC: bd/BD/ip/BD_axi_timer_2_0/BD_axi_timer_2_0_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_2 || ORIG_REF_NAME==BD_dlmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_2 || ORIG_REF_NAME==BD_ilmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_bram_if_cntlr_2/BD_dlmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_bram_if_cntlr_2/BD_ilmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/BD/ip/BD_lmb_bram_2/BD_lmb_bram_2_ooc.xdc

# XDC: bd/BD/ip/BD_xbar_2/BD_xbar_2_ooc.xdc

# XDC: bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_dpr_0 || ORIG_REF_NAME==BD_pio_dpr_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_dpr_0 || ORIG_REF_NAME==BD_pio_dpr_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_cpu_1_0_0 || ORIG_REF_NAME==BD_cpu_1_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0_ooc_debug.xdc

# XDC: bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_1_0_0 || ORIG_REF_NAME==BD_pio_1_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0_ooc.xdc

# XDC: bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_pio_1_0_0 || ORIG_REF_NAME==BD_pio_1_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_axi_timer_3_0/BD_axi_timer_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_3_0 || ORIG_REF_NAME==BD_axi_timer_3_0}]

# XDC: bd/BD/ip/BD_axi_timer_3_0/BD_axi_timer_3_0_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_v10_3/BD_dlmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_3 || ORIG_REF_NAME==BD_dlmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_dlmb_v10_3/BD_dlmb_v10_3_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_v10_3/BD_ilmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_3 || ORIG_REF_NAME==BD_ilmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/BD/ip/BD_ilmb_v10_3/BD_ilmb_v10_3_ooc.xdc

# XDC: bd/BD/ip/BD_dlmb_bram_if_cntlr_3/BD_dlmb_bram_if_cntlr_3_ooc.xdc

# XDC: bd/BD/ip/BD_ilmb_bram_if_cntlr_3/BD_ilmb_bram_if_cntlr_3_ooc.xdc

# XDC: bd/BD/ip/BD_lmb_bram_3/BD_lmb_bram_3_ooc.xdc

# XDC: bd/BD/ip/BD_xbar_3/BD_xbar_3_ooc.xdc

# XDC: bd/BD/BD_ooc.xdc
