# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0.xci
# IP: The module: 'BD_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0.xci
# IP: The module: 'BD_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/git/NoC/programmableCh/dfs/project/project.srcs/sources_1/bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
