# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/dfs/constraints.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD}]

# IP: bd/BD/ip/BD_axi_gpio_1_0/BD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_gpio_1_0 || ORIG_REF_NAME==BD_axi_gpio_1_0}]

# IP: bd/BD/ip/BD_axi_gpio_2_0/BD_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_gpio_2_0 || ORIG_REF_NAME==BD_axi_gpio_2_0}]

# IP: bd/BD/ip/BD_axi_gpio_3_0/BD_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_gpio_3_0 || ORIG_REF_NAME==BD_axi_gpio_3_0}]

# IP: bd/BD/ip/BD_axi_pwm_pause_1_0/BD_axi_pwm_pause_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_pwm_pause_1_0 || ORIG_REF_NAME==BD_axi_pwm_pause_1_0}]

# IP: bd/BD/ip/BD_axi_pwm_pause_2_0/BD_axi_pwm_pause_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_pwm_pause_2_0 || ORIG_REF_NAME==BD_axi_pwm_pause_2_0}]

# IP: bd/BD/ip/BD_axi_pwm_pause_3_0/BD_axi_pwm_pause_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_pwm_pause_3_0 || ORIG_REF_NAME==BD_axi_pwm_pause_3_0}]

# IP: bd/BD/ip/BD_microblaze_1_0/BD_microblaze_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_1_0 || ORIG_REF_NAME==BD_microblaze_1_0}]

# IP: bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_0 || ORIG_REF_NAME==BD_dlmb_v10_0}]

# IP: bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_0 || ORIG_REF_NAME==BD_ilmb_v10_0}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_0/BD_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_0}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_0/BD_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_0}]

# IP: bd/BD/ip/BD_lmb_bram_0/BD_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_0 || ORIG_REF_NAME==BD_lmb_bram_0}]

# IP: bd/BD/ip/BD_microblaze_1_axi_periph_0/BD_microblaze_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_1_axi_periph_0 || ORIG_REF_NAME==BD_microblaze_1_axi_periph_0}]

# IP: bd/BD/ip/BD_microblaze_1_axi_intc_0/BD_microblaze_1_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_1_axi_intc_0 || ORIG_REF_NAME==BD_microblaze_1_axi_intc_0}]

# IP: bd/BD/ip/BD_microblaze_1_xlconcat_0/BD_microblaze_1_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_1_xlconcat_0 || ORIG_REF_NAME==BD_microblaze_1_xlconcat_0}]

# IP: bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_mdm_1_0 || ORIG_REF_NAME==BD_mdm_1_0}]

# IP: bd/BD/ip/BD_rst_clk_wiz_0_100M_0/BD_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==BD_rst_clk_wiz_0_100M_0}]

# IP: bd/BD/ip/BD_microblaze_2_0/BD_microblaze_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_2_0 || ORIG_REF_NAME==BD_microblaze_2_0}]

# IP: bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_1 || ORIG_REF_NAME==BD_dlmb_v10_1}]

# IP: bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_1 || ORIG_REF_NAME==BD_ilmb_v10_1}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_1/BD_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_1}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_1/BD_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_1}]

# IP: bd/BD/ip/BD_lmb_bram_1/BD_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_1 || ORIG_REF_NAME==BD_lmb_bram_1}]

# IP: bd/BD/ip/BD_microblaze_2_axi_periph_0/BD_microblaze_2_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_2_axi_periph_0 || ORIG_REF_NAME==BD_microblaze_2_axi_periph_0}]

# IP: bd/BD/ip/BD_microblaze_2_axi_intc_0/BD_microblaze_2_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_2_axi_intc_0 || ORIG_REF_NAME==BD_microblaze_2_axi_intc_0}]

# IP: bd/BD/ip/BD_microblaze_2_xlconcat_0/BD_microblaze_2_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_2_xlconcat_0 || ORIG_REF_NAME==BD_microblaze_2_xlconcat_0}]

# IP: bd/BD/ip/BD_microblaze_3_0/BD_microblaze_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_3_0 || ORIG_REF_NAME==BD_microblaze_3_0}]

# IP: bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_v10_2 || ORIG_REF_NAME==BD_dlmb_v10_2}]

# IP: bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_v10_2 || ORIG_REF_NAME==BD_ilmb_v10_2}]

# IP: bd/BD/ip/BD_dlmb_bram_if_cntlr_2/BD_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==BD_dlmb_bram_if_cntlr_2}]

# IP: bd/BD/ip/BD_ilmb_bram_if_cntlr_2/BD_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==BD_ilmb_bram_if_cntlr_2}]

# IP: bd/BD/ip/BD_lmb_bram_2/BD_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_lmb_bram_2 || ORIG_REF_NAME==BD_lmb_bram_2}]

# IP: bd/BD/ip/BD_microblaze_3_axi_periph_0/BD_microblaze_3_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_3_axi_periph_0 || ORIG_REF_NAME==BD_microblaze_3_axi_periph_0}]

# IP: bd/BD/ip/BD_microblaze_3_axi_intc_0/BD_microblaze_3_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_3_axi_intc_0 || ORIG_REF_NAME==BD_microblaze_3_axi_intc_0}]

# IP: bd/BD/ip/BD_microblaze_3_xlconcat_0/BD_microblaze_3_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_microblaze_3_xlconcat_0 || ORIG_REF_NAME==BD_microblaze_3_xlconcat_0}]

# IP: bd/BD/ip/BD_util_vector_logic_0_0/BD_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_util_vector_logic_0_0 || ORIG_REF_NAME==BD_util_vector_logic_0_0}]

# IP: bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_processing_system7_0_0 || ORIG_REF_NAME==BD_processing_system7_0_0}]

# IP: bd/BD/ip/BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0/BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0 || ORIG_REF_NAME==BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0}]

# IP: bd/BD/ip/BD_xbar_0/BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_0 || ORIG_REF_NAME==BD_xbar_0}]

# IP: bd/BD/ip/BD_xbar_1/BD_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_1 || ORIG_REF_NAME==BD_xbar_1}]

# IP: bd/BD/ip/BD_xbar_2/BD_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_2 || ORIG_REF_NAME==BD_xbar_2}]

# IP: bd/BD/ip/BD_ps7_0_axi_periph_0/BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==BD_ps7_0_axi_periph_0}]

# IP: bd/BD/ip/BD_axi_interconnect_0_0/BD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_interconnect_0_0 || ORIG_REF_NAME==BD_axi_interconnect_0_0}]

# IP: bd/BD/ip/BD_xbar_3/BD_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_3 || ORIG_REF_NAME==BD_xbar_3}]

# IP: bd/BD/ip/BD_axi_protocol_converter_0_0/BD_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_protocol_converter_0_0 || ORIG_REF_NAME==BD_axi_protocol_converter_0_0}]

# IP: bd/BD/ip/BD_xbar_4/BD_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_xbar_4 || ORIG_REF_NAME==BD_xbar_4}]

# IP: bd/BD/ip/BD_axi_perf_mon_0_0/BD_axi_perf_mon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_perf_mon_0_0 || ORIG_REF_NAME==BD_axi_perf_mon_0_0}]

# IP: bd/BD/ip/BD_axi_perf_mon_1_0/BD_axi_perf_mon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_perf_mon_1_0 || ORIG_REF_NAME==BD_axi_perf_mon_1_0}]

# IP: bd/BD/ip/BD_axi_perf_mon_2_0/BD_axi_perf_mon_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_perf_mon_2_0 || ORIG_REF_NAME==BD_axi_perf_mon_2_0}]

# IP: bd/BD/ip/BD_axi_perf_mon_3_0/BD_axi_perf_mon_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_perf_mon_3_0 || ORIG_REF_NAME==BD_axi_perf_mon_3_0}]

# IP: bd/BD/ip/BD_axi_timer_0_0/BD_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_0_0 || ORIG_REF_NAME==BD_axi_timer_0_0}]

# IP: bd/BD/ip/BD_axi_timer_1_0/BD_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_1_0 || ORIG_REF_NAME==BD_axi_timer_1_0}]

# IP: bd/BD/ip/BD_axi_timer_2_0/BD_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_2_0 || ORIG_REF_NAME==BD_axi_timer_2_0}]

# IP: bd/BD/ip/BD_axi_timer_3_0/BD_axi_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_timer_3_0 || ORIG_REF_NAME==BD_axi_timer_3_0}]

# IP: bd/BD/ip/BD_axi_clock_converter_mdm_0/BD_axi_clock_converter_mdm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_clock_converter_mdm_0 || ORIG_REF_NAME==BD_axi_clock_converter_mdm_0}]

# IP: bd/BD/ip/BD_axi_clock_converter_ni0_0/BD_axi_clock_converter_ni0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_clock_converter_ni0_0 || ORIG_REF_NAME==BD_axi_clock_converter_ni0_0}]

# IP: bd/BD/ip/BD_axi_clock_converter_ni1_0/BD_axi_clock_converter_ni1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_clock_converter_ni1_0 || ORIG_REF_NAME==BD_axi_clock_converter_ni1_0}]

# IP: bd/BD/ip/BD_axi_clock_converter_ni2_0/BD_axi_clock_converter_ni2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_clock_converter_ni2_0 || ORIG_REF_NAME==BD_axi_clock_converter_ni2_0}]

# IP: bd/BD/ip/BD_axi_clock_converter_ni3_0/BD_axi_clock_converter_ni3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_clock_converter_ni3_0 || ORIG_REF_NAME==BD_axi_clock_converter_ni3_0}]

# IP: bd/BD/ip/BD_util_vector_logic_1_0/BD_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_util_vector_logic_1_0 || ORIG_REF_NAME==BD_util_vector_logic_1_0}]

# IP: bd/BD/ip/BD_s00_data_fifo_0/BD_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_s00_data_fifo_0 || ORIG_REF_NAME==BD_s00_data_fifo_0}]

# IP: bd/BD/ip/BD_s01_data_fifo_0/BD_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_s01_data_fifo_0 || ORIG_REF_NAME==BD_s01_data_fifo_0}]

# IP: bd/BD/ip/BD_s02_data_fifo_0/BD_s02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_s02_data_fifo_0 || ORIG_REF_NAME==BD_s02_data_fifo_0}]

# IP: bd/BD/ip/BD_s03_data_fifo_0/BD_s03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_s03_data_fifo_0 || ORIG_REF_NAME==BD_s03_data_fifo_0}]

# IP: bd/BD/ip/BD_m00_data_fifo_0/BD_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_m00_data_fifo_0 || ORIG_REF_NAME==BD_m00_data_fifo_0}]

# IP: bd/BD/ip/BD_auto_pc_0/BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_auto_pc_0 || ORIG_REF_NAME==BD_auto_pc_0}]

# IP: bd/BD/ip/BD_auto_pc_1/BD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_auto_pc_1 || ORIG_REF_NAME==BD_auto_pc_1}]

# IP: bd/BD/ip/BD_auto_pc_2/BD_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_auto_pc_2 || ORIG_REF_NAME==BD_auto_pc_2}]

# IP: bd/BD/ip/BD_auto_pc_3/BD_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_auto_pc_3 || ORIG_REF_NAME==BD_auto_pc_3}]

# XDC: bd/BD/BD_ooc.xdc
