#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : BD.sh
# Simulator   : Cadence Incisive Enterprise Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Aug 01 16:21:05 CEST 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: BD.sh [-help]
# usage: BD.sh [-lib_map_path]
# usage: BD.sh [-noclean_files]
# usage: BD.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'BD.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "BD.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: BD.sh [-help]\n\
Usage: BD.sh [-lib_map_path]\n\
Usage: BD.sh [-reset_run]\n\
Usage: BD.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./BD.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./BD.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     touch hdl.var
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     touch hdl.var
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ncsim.key irun.key ncvlog.log ncvhdl.log compile.log elaborate.log simulate.log run.log waves.shm INCA_libs)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib microblaze_v9_5_3 kth_axi_rni_static_v1_00_a proc_common_v3_00_a axi_lite_ipif_v1_01_a axi_lite_ipif_v3_0_3 lib_cdc_v1_0_2 interrupt_control_v3_1_3 axi_gpio_v2_0_9 lib_pkg_v1_0_2 axi_timer_v2_0_8 lmb_v10_v3_0_7 lmb_bram_if_cntlr_v4_0_7 blk_mem_gen_v8_3_1 mdm_v3_2_4 proc_sys_reset_v5_0_8 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_7 fifo_generator_v13_0_1 axi_data_fifo_v2_1_6 axi_crossbar_v2_1_8 util_vector_logic_v2_0 kth_2dnoc_2x2x1_v1_00_a)
  file="cds.lib"
  dir="ies"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="INCLUDE $lib_map_path/cds.lib"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="DEFINE $lib $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-64bit -messages -logfile ncvlog.log -append_log"
  opts_vhd="-64bit -V93 -RELAX -logfile ncvhdl.log -append_log"

  # Compile design files
  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0.v" \

  ncvhdl -work microblaze_v9_5_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/microblaze_v9_5/hdl/microblaze_v9_5_vh_rfs.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_cpu_0_0_0/sim/BD_cpu_0_0_0.vhd" \

  ncvhdl -work kth_axi_rni_static_v1_00_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/NoC_3D_parallel_package.vhd" \

  ncvhdl -work proc_common_v3_00_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/proc_common_pkg.vhd" \

  ncvhdl -work kth_axi_rni_static_v1_00_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/generic_interface_to_noc_static.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/NoC_3D_SW_configuration_package.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/kth_generic_rni_static.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/kth_axi_rni_static_v1_0.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/kth_axi_rni_static.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/rni_memory_64_32.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/rni_memory.vhd" \

  ncvhdl -work proc_common_v3_00_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/ipif_pkg.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/pselect_f.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/family_support.vhd" \

  ncvhdl -work axi_lite_ipif_v1_01_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/slave_attachment.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_axi_rni_static_c1_v1_0/hdl/address_decoder.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_kth_axi_rni_static_c1_0_0/sim/BD_kth_axi_rni_static_c1_0_0.vhd" \

  ncvhdl -work axi_lite_ipif_v3_0_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd" \

  ncvhdl -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \

  ncvhdl -work interrupt_control_v3_1_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/interrupt_control_v3_1/hdl/src/vhdl/interrupt_control.vhd" \

  ncvhdl -work axi_gpio_v2_0_9 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_gpio_v2_0/hdl/src/vhdl/gpio_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_gpio_v2_0/hdl/src/vhdl/axi_gpio.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_axi_gpio_0_0/sim/BD_axi_gpio_0_0.vhd" \

  ncvhdl -work lib_pkg_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd" \

  ncvhdl -work axi_timer_v2_0_8 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/counter_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/mux_onehot_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/tc_types.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/timer_control.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/count_module.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/tc_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/axi_timer.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_axi_timer_0_0/sim/BD_axi_timer_0_0.vhd" \

  ncvhdl -work lmb_v10_v3_0_7 $opts_vhd \
    "$ref_dir/../../../ipstatic/lmb_v10_v3_0/hdl/vhdl/lmb_v10.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_v10_0/sim/BD_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_v10_0/sim/BD_ilmb_v10_0.vhd" \

  ncvhdl -work lmb_bram_if_cntlr_v4_0_7 $opts_vhd \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_funcs.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_primitives.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/xor18.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/parity.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/parityenable.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/checkbit_handler.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/correct_one_bit.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/pselect.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/pselect_mask.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/axi_interface.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_mux.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_cntlr.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_bram_if_cntlr_0/sim/BD_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_bram_if_cntlr_0/sim/BD_ilmb_bram_if_cntlr_0.vhd" \

  ncvhdl -work blk_mem_gen_v8_3_1 $opts_vhd \
    "$ref_dir/../../../ipstatic/blk_mem_gen_v8_3/simulation/blk_mem_gen_v8_3.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_lmb_bram_0/sim/BD_lmb_bram_0.vhd" \

  ncvhdl -work mdm_v3_2_4 $opts_vhd \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm_primitives.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/arbiter.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/srl_fifo.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/bus_master.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/jtag_control.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm_core.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_mdm_1_0/sim/BD_mdm_1_0.vhd" \

  ncvhdl -work proc_sys_reset_v5_0_8 $opts_vhd \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_rst_clk_wiz_50M_0/sim/BD_rst_clk_wiz_50M_0.vhd" \

  ncvlog -work generic_baseblocks_v2_1_0 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \

  ncvlog -work axi_infrastructure_v1_1_0 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \

  ncvlog -work axi_register_slice_v2_1_7 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \

  ncvhdl -work fifo_generator_v13_0_1 $opts_vhd \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/hdl/fifo_generator_v13_0_rfs.vhd" \

  ncvlog -work axi_data_fifo_v2_1_6 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \

  ncvlog -work axi_crossbar_v2_1_8 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/BD/ip/BD_xbar_0/sim/BD_xbar_0.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_microblaze_0_0/sim/BD_microblaze_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_kth_axi_rni_static_c1_0_1/sim/BD_kth_axi_rni_static_c1_0_1.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_pio_0_0_0/sim/BD_pio_0_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_timer_1_0/sim/BD_axi_timer_1_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_v10_1/sim/BD_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_v10_1/sim/BD_ilmb_v10_1.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_bram_if_cntlr_1/sim/BD_dlmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_bram_if_cntlr_1/sim/BD_ilmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_lmb_bram_1/sim/BD_lmb_bram_1.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/BD/ip/BD_xbar_1/sim/BD_xbar_1.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_cpu_0_1_0/sim/BD_cpu_0_1_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_kth_axi_rni_static_c1_1_0/sim/BD_kth_axi_rni_static_c1_1_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_pio_0_1_0/sim/BD_pio_0_1_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_timer_2_0/sim/BD_axi_timer_2_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_v10_2/sim/BD_dlmb_v10_2.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_v10_2/sim/BD_ilmb_v10_2.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_bram_if_cntlr_2/sim/BD_dlmb_bram_if_cntlr_2.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_bram_if_cntlr_2/sim/BD_ilmb_bram_if_cntlr_2.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_lmb_bram_2/sim/BD_lmb_bram_2.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/BD/ip/BD_xbar_2/sim/BD_xbar_2.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_pio_dpr_0/sim/BD_pio_dpr_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_cpu_1_0_0/sim/BD_cpu_1_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_kth_axi_rni_static_c1_2_0/sim/BD_kth_axi_rni_static_c1_2_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_pio_1_0_0/sim/BD_pio_1_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_timer_3_0/sim/BD_axi_timer_3_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_v10_3/sim/BD_dlmb_v10_3.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_v10_3/sim/BD_ilmb_v10_3.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_dlmb_bram_if_cntlr_3/sim/BD_dlmb_bram_if_cntlr_3.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_ilmb_bram_if_cntlr_3/sim/BD_ilmb_bram_if_cntlr_3.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_lmb_bram_3/sim/BD_lmb_bram_3.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/BD/ip/BD_xbar_3/sim/BD_xbar_3.v" \

  ncvhdl -work util_vector_logic_v2_0 $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/xilinx.com/util_vector_logic_v2_0/hdl/util_vector_logic.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_inverter_0/sim/BD_inverter_0.vhd" \

  ncvhdl -work kth_2DNoC_2x2x1_v1_00_a $opts_vhd \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/kth_2DNoC_2x2x1_v1_0.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/NoC_3D_parallel_package.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/NoC_2D_Parallel.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/NoC_3D_parallel_switch.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/NoC_3D_parallel_recv.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/kth.se/kth_2dnoc_2x2x1_c1_v1_0/hdl/NoC_3D_parallel_xmitter.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/BD/ip/BD_kth_2DNoC_2x2x1_c1_0_0/sim/BD_kth_2DNoC_2x2x1_c1_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ipshared/xilinx.com/xlconstant_v1_1/xlconstant.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_xlconstant_0_0/sim/BD_xlconstant_0_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_Ground_1_0/sim/BD_Ground_1_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_Ground_8_0/sim/BD_Ground_8_0.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_Ground_15_0/sim/BD_Ground_15_0.vhd" \
    "$ref_dir/../../../bd/BD/hdl/BD.vhd" \


  ncvlog $opts_ver -work xil_defaultlib \
    "glbl.v"

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-64bit -relax -access +rwc -messages -logfile elaborate.log -timescale 1ps/1ps"
  libs="-libname unisims_ver -libname unimacro_ver -libname secureip -libname xil_defaultlib -libname microblaze_v9_5_3 -libname kth_axi_rni_static_v1_00_a -libname proc_common_v3_00_a -libname axi_lite_ipif_v1_01_a -libname axi_lite_ipif_v3_0_3 -libname lib_cdc_v1_0_2 -libname interrupt_control_v3_1_3 -libname axi_gpio_v2_0_9 -libname lib_pkg_v1_0_2 -libname axi_timer_v2_0_8 -libname lmb_v10_v3_0_7 -libname lmb_bram_if_cntlr_v4_0_7 -libname blk_mem_gen_v8_3_1 -libname mdm_v3_2_4 -libname proc_sys_reset_v5_0_8 -libname generic_baseblocks_v2_1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_7 -libname fifo_generator_v13_0_1 -libname axi_data_fifo_v2_1_6 -libname axi_crossbar_v2_1_8 -libname util_vector_logic_v2_0 -libname kth_2dnoc_2x2x1_v1_00_a"
  ncelab $opts xil_defaultlib.BD xil_defaultlib.glbl $libs
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-64bit -logfile simulate.log"
  ncsim $opts xil_defaultlib.BD -input simulate.do
}
# Script usage
usage()
{
  msg="Usage: BD.sh [-help]\n\
Usage: BD.sh [-lib_map_path]\n\
Usage: BD.sh [-reset_run]\n\
Usage: BD.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
