set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_0_0_0/BD_cpu_0_0_0.xdc id:1 order:EARLY scoped_inst:BD_i/cpu_0_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_mdm_1_0/BD_mdm_1_0.xdc id:2 order:EARLY scoped_inst:BD_i/mdm_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_microblaze_0_0/BD_microblaze_0_0.xdc id:3 order:EARLY scoped_inst:BD_i/cpu_0_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_0_1_0/BD_cpu_0_1_0.xdc id:4 order:EARLY scoped_inst:BD_i/cpu_1_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_cpu_1_0_0/BD_cpu_1_0_0.xdc id:5 order:EARLY scoped_inst:BD_i/cpu_1_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_clk_wiz_0/BD_clk_wiz_0.xdc id:7 order:EARLY scoped_inst:BD_i/clk_wiz/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0.xdc id:8 order:EARLY scoped_inst:BD_i/pio_0_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_0/BD_dlmb_v10_0.xdc id:9 order:EARLY scoped_inst:BD_i/cpu_0_0_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_0/BD_ilmb_v10_0.xdc id:10 order:EARLY scoped_inst:BD_i/cpu_0_0_local_memory/ilmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_rst_clk_wiz_50M_0/BD_rst_clk_wiz_50M_0.xdc id:11 order:EARLY scoped_inst:BD_i/sys_rst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_0_0_0/BD_pio_0_0_0.xdc id:12 order:EARLY scoped_inst:BD_i/pio_0_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_1/BD_dlmb_v10_1.xdc id:13 order:EARLY scoped_inst:BD_i/cpu_0_1_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_1/BD_ilmb_v10_1.xdc id:14 order:EARLY scoped_inst:BD_i/cpu_0_1_local_memory/ilmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_0_1_0/BD_pio_0_1_0.xdc id:15 order:EARLY scoped_inst:BD_i/pio_1_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_2/BD_dlmb_v10_2.xdc id:16 order:EARLY scoped_inst:BD_i/cpu_1_0_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_2/BD_ilmb_v10_2.xdc id:17 order:EARLY scoped_inst:BD_i/cpu_1_0_local_memory/ilmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_dpr_0/BD_pio_dpr_0.xdc id:18 order:EARLY scoped_inst:BD_i/pio_dpr/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_pio_1_0_0/BD_pio_1_0_0.xdc id:19 order:EARLY scoped_inst:BD_i/pio_1_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_3/BD_dlmb_v10_3.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_3/BD_dlmb_v10_3.xdc id:20 order:EARLY scoped_inst:BD_i/cpu_1_1_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tage/DegreeProject/Zedboard/NoC2xD/NoC2x2_100KHz_c1_D/NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_3/BD_ilmb_v10_3.xdc rfile:../../../../../NoC2x2_100KHz_AltenDemo_c1_D.srcs/sources_1/bd/BD/ip/BD_ilmb_v10_3/BD_ilmb_v10_3.xdc id:21 order:EARLY scoped_inst:BD_i/cpu_1_1_local_memory/ilmb_v10/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
current_instance BD_i/cpu_0_0/U0
set_ip_msg_config -idlist {CDC-1 CDC-4 CDC-7 DPOP-3 TIMING-10 TIMING-9}
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
current_instance BD_i/mdm_1/U0
set_ip_msg_config -idlist {CDC-1 CDCM-1 REQP-1851 TIMING-10 TIMING-14 TIMING-2 TIMING-4 TIMING-9}
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
current_instance BD_i/cpu_0_1/U0
set_ip_msg_config -idlist {CDC-1 CDC-4 CDC-7 DPOP-3 TIMING-10 TIMING-9}
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
current_instance BD_i/cpu_1_0/U0
set_ip_msg_config -idlist {CDC-1 CDC-4 CDC-7 DPOP-3 TIMING-10 TIMING-9}
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
current_instance BD_i/cpu_1_1/U0
set_ip_msg_config -idlist {CDC-1 CDC-4 CDC-7 DPOP-3 TIMING-10 TIMING-9}
current_instance
set_property src_info {type:XDC file:6 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/clk_wiz/inst]
set_property src_info {type:XDC file:6 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0/U0]
set_property src_info {type:XDC file:6 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_0_0/U0]
set_property src_info {type:XDC file:6 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:6 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/ilmb_v10/U0]
set_property src_info {type:XDC file:6 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/mdm_1/U0]
set_property src_info {type:XDC file:6 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1/U0]
set_property src_info {type:XDC file:6 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_0_1/U0]
set_property src_info {type:XDC file:6 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:6 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/ilmb_v10/U0]
set_property src_info {type:XDC file:6 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0/U0]
set_property src_info {type:XDC file:6 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_1_0/U0]
set_property src_info {type:XDC file:6 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:6 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/ilmb_v10/U0]
set_property src_info {type:XDC file:6 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_dpr/U0]
set_property src_info {type:XDC file:6 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1/U0]
set_property src_info {type:XDC file:6 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_1_1/U0]
set_property src_info {type:XDC file:6 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:6 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/ilmb_v10/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/Ground_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/Ground_15]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/Ground_64]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/Ground_8]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/clk_wiz]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_0_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_0_1_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_0_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/cpu_1_1_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/inverter]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/kth_2DNoC_2x2x1_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/kth_axi_rni_static_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/kth_axi_rni_static_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/kth_axi_rni_static_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/kth_axi_rni_static_3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/mdm_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_0_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_0_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_1_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_1_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/pio_dpr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells BD_i/sys_rst]
set_property src_info {type:SCOPED_XDC file:7 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name GCLK [get_ports GCLK]
current_instance BD_i/cpu_0_0/U0
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins MicroBlaze_Core_I/Reset_DFF/*/D]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {BD_i/pio_0_0/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS4/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D} {BD_i/pio_0_0/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS5/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_0_0_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_0_0_local_memory/ilmb_v10/U0/SYS_Rst]
current_instance BD_i/mdm_1/U0
set_property src_info {type:SCOPED_XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name BD_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK [get_pins Use*.BSCAN*/DRCK]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name BD_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE [get_pins Use*.BSCAN*/UPDATE]
current_instance
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_BD_clk_wiz_0 -source [get_pins BD_i/clk_wiz/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock GCLK [get_pins BD_i/clk_wiz/inst/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out1_BD_clk_wiz_0 -source [get_pins BD_i/clk_wiz/inst/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} -add -master_clock GCLK [get_pins BD_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks BD_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks BD_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE]
current_instance BD_i/mdm_1/U0
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins Use*.BSCAN*/CAPTURE]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins Use*.BSCAN*/SEL]
set_property src_info {type:SCOPED_XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins Use*.BSCAN*/SHIFT]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins Use*.BSCAN*/TDI]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -logically_exclusive -group [get_clocks BD_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK] -group [get_clocks BD_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE]
set_property src_info {type:SCOPED_XDC file:11 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list BD_i/sys_rst/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D BD_i/sys_rst/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
current_instance BD_i/cpu_0_1/U0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins MicroBlaze_Core_I/Reset_DFF/*/D]
current_instance
set_property src_info {type:SCOPED_XDC file:12 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {BD_i/pio_0_1/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS4/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D} {BD_i/pio_0_1/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS5/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_0_1_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_0_1_local_memory/ilmb_v10/U0/SYS_Rst]
current_instance BD_i/cpu_1_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins MicroBlaze_Core_I/Reset_DFF/*/D]
current_instance
set_property src_info {type:SCOPED_XDC file:15 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {BD_i/pio_1_0/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS4/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D} {BD_i/pio_1_0/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS5/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_1_0_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_1_0_local_memory/ilmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:18 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {BD_i/pio_dpr/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS4/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D} {BD_i/pio_dpr/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS5/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]]
current_instance BD_i/cpu_1_1/U0
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins MicroBlaze_Core_I/Reset_DFF/*/D]
current_instance
set_property src_info {type:SCOPED_XDC file:19 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {BD_i/pio_1_1/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS4/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D} {BD_i/pio_1_1/U0/gpio_core_1/Dual.INPUT_DOUBLE_REGS5/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[0].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_1_1_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins BD_i/cpu_1_1_local_memory/ilmb_v10/U0/SYS_Rst]
