-- (c) Copyright 1995-2017 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: kth.se:tage:kth_axi_Mesh_2D_Nostrum_2x2x1:1.0
-- IP Revision: 4

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0 IS
  PORT (
    NoC_Irq_0 : OUT STD_LOGIC;
    S_AXI_0_ACLK : IN STD_LOGIC;
    S_AXI_0_ARESETN : IN STD_LOGIC;
    S_AXI_0_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_0_AWVALID : IN STD_LOGIC;
    S_AXI_0_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_0_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_0_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S_AXI_0_WVALID : IN STD_LOGIC;
    S_AXI_0_BREADY : IN STD_LOGIC;
    S_AXI_0_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_0_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_0_ARVALID : IN STD_LOGIC;
    S_AXI_0_RREADY : IN STD_LOGIC;
    S_AXI_0_ARREADY : OUT STD_LOGIC;
    S_AXI_0_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_0_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_0_RVALID : OUT STD_LOGIC;
    S_AXI_0_WREADY : OUT STD_LOGIC;
    S_AXI_0_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_0_BVALID : OUT STD_LOGIC;
    S_AXI_0_AWREADY : OUT STD_LOGIC;
    NoC_Irq_1 : OUT STD_LOGIC;
    S_AXI_1_ACLK : IN STD_LOGIC;
    S_AXI_1_ARESETN : IN STD_LOGIC;
    S_AXI_1_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_1_AWVALID : IN STD_LOGIC;
    S_AXI_1_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_1_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_1_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S_AXI_1_WVALID : IN STD_LOGIC;
    S_AXI_1_BREADY : IN STD_LOGIC;
    S_AXI_1_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_1_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_1_ARVALID : IN STD_LOGIC;
    S_AXI_1_RREADY : IN STD_LOGIC;
    S_AXI_1_ARREADY : OUT STD_LOGIC;
    S_AXI_1_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_1_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_1_RVALID : OUT STD_LOGIC;
    S_AXI_1_WREADY : OUT STD_LOGIC;
    S_AXI_1_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_1_BVALID : OUT STD_LOGIC;
    S_AXI_1_AWREADY : OUT STD_LOGIC;
    NoC_Irq_2 : OUT STD_LOGIC;
    S_AXI_2_ACLK : IN STD_LOGIC;
    S_AXI_2_ARESETN : IN STD_LOGIC;
    S_AXI_2_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_2_AWVALID : IN STD_LOGIC;
    S_AXI_2_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_2_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_2_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S_AXI_2_WVALID : IN STD_LOGIC;
    S_AXI_2_BREADY : IN STD_LOGIC;
    S_AXI_2_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_2_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_2_ARVALID : IN STD_LOGIC;
    S_AXI_2_RREADY : IN STD_LOGIC;
    S_AXI_2_ARREADY : OUT STD_LOGIC;
    S_AXI_2_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_2_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_2_RVALID : OUT STD_LOGIC;
    S_AXI_2_WREADY : OUT STD_LOGIC;
    S_AXI_2_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_2_BVALID : OUT STD_LOGIC;
    S_AXI_2_AWREADY : OUT STD_LOGIC;
    NoC_Irq_3 : OUT STD_LOGIC;
    S_AXI_3_ACLK : IN STD_LOGIC;
    S_AXI_3_ARESETN : IN STD_LOGIC;
    S_AXI_3_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_3_AWVALID : IN STD_LOGIC;
    S_AXI_3_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_3_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_3_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S_AXI_3_WVALID : IN STD_LOGIC;
    S_AXI_3_BREADY : IN STD_LOGIC;
    S_AXI_3_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
    S_AXI_3_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S_AXI_3_ARVALID : IN STD_LOGIC;
    S_AXI_3_RREADY : IN STD_LOGIC;
    S_AXI_3_ARREADY : OUT STD_LOGIC;
    S_AXI_3_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S_AXI_3_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_3_RVALID : OUT STD_LOGIC;
    S_AXI_3_WREADY : OUT STD_LOGIC;
    S_AXI_3_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S_AXI_3_BVALID : OUT STD_LOGIC;
    S_AXI_3_AWREADY : OUT STD_LOGIC
  );
END BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0;

ARCHITECTURE BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0_arch OF BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0_arch: ARCHITECTURE IS "yes";
  COMPONENT kth_axi_Mesh_2D_Nostrum_2x2x1 IS
    GENERIC (
      C_S00_AXI_BASEADDR : INTEGER;
      C_S00_AXI_HIGHADDR : INTEGER;
      C_S01_AXI_BASEADDR : INTEGER;
      C_S01_AXI_HIGHADDR : INTEGER;
      C_S02_AXI_BASEADDR : INTEGER;
      C_S02_AXI_HIGHADDR : INTEGER;
      C_S03_AXI_BASEADDR : INTEGER;
      C_S03_AXI_HIGHADDR : INTEGER
    );
    PORT (
      NoC_Irq_0 : OUT STD_LOGIC;
      S_AXI_0_ACLK : IN STD_LOGIC;
      S_AXI_0_ARESETN : IN STD_LOGIC;
      S_AXI_0_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_0_AWVALID : IN STD_LOGIC;
      S_AXI_0_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_0_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_0_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S_AXI_0_WVALID : IN STD_LOGIC;
      S_AXI_0_BREADY : IN STD_LOGIC;
      S_AXI_0_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_0_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_0_ARVALID : IN STD_LOGIC;
      S_AXI_0_RREADY : IN STD_LOGIC;
      S_AXI_0_ARREADY : OUT STD_LOGIC;
      S_AXI_0_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_0_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_0_RVALID : OUT STD_LOGIC;
      S_AXI_0_WREADY : OUT STD_LOGIC;
      S_AXI_0_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_0_BVALID : OUT STD_LOGIC;
      S_AXI_0_AWREADY : OUT STD_LOGIC;
      NoC_Irq_1 : OUT STD_LOGIC;
      S_AXI_1_ACLK : IN STD_LOGIC;
      S_AXI_1_ARESETN : IN STD_LOGIC;
      S_AXI_1_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_1_AWVALID : IN STD_LOGIC;
      S_AXI_1_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_1_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_1_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S_AXI_1_WVALID : IN STD_LOGIC;
      S_AXI_1_BREADY : IN STD_LOGIC;
      S_AXI_1_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_1_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_1_ARVALID : IN STD_LOGIC;
      S_AXI_1_RREADY : IN STD_LOGIC;
      S_AXI_1_ARREADY : OUT STD_LOGIC;
      S_AXI_1_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_1_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_1_RVALID : OUT STD_LOGIC;
      S_AXI_1_WREADY : OUT STD_LOGIC;
      S_AXI_1_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_1_BVALID : OUT STD_LOGIC;
      S_AXI_1_AWREADY : OUT STD_LOGIC;
      NoC_Irq_2 : OUT STD_LOGIC;
      S_AXI_2_ACLK : IN STD_LOGIC;
      S_AXI_2_ARESETN : IN STD_LOGIC;
      S_AXI_2_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_2_AWVALID : IN STD_LOGIC;
      S_AXI_2_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_2_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_2_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S_AXI_2_WVALID : IN STD_LOGIC;
      S_AXI_2_BREADY : IN STD_LOGIC;
      S_AXI_2_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_2_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_2_ARVALID : IN STD_LOGIC;
      S_AXI_2_RREADY : IN STD_LOGIC;
      S_AXI_2_ARREADY : OUT STD_LOGIC;
      S_AXI_2_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_2_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_2_RVALID : OUT STD_LOGIC;
      S_AXI_2_WREADY : OUT STD_LOGIC;
      S_AXI_2_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_2_BVALID : OUT STD_LOGIC;
      S_AXI_2_AWREADY : OUT STD_LOGIC;
      NoC_Irq_3 : OUT STD_LOGIC;
      S_AXI_3_ACLK : IN STD_LOGIC;
      S_AXI_3_ARESETN : IN STD_LOGIC;
      S_AXI_3_AWADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_3_AWVALID : IN STD_LOGIC;
      S_AXI_3_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_3_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_3_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S_AXI_3_WVALID : IN STD_LOGIC;
      S_AXI_3_BREADY : IN STD_LOGIC;
      S_AXI_3_ARADDR : IN STD_LOGIC_VECTOR(16 DOWNTO 0);
      S_AXI_3_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S_AXI_3_ARVALID : IN STD_LOGIC;
      S_AXI_3_RREADY : IN STD_LOGIC;
      S_AXI_3_ARREADY : OUT STD_LOGIC;
      S_AXI_3_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S_AXI_3_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_3_RVALID : OUT STD_LOGIC;
      S_AXI_3_WREADY : OUT STD_LOGIC;
      S_AXI_3_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S_AXI_3_BVALID : OUT STD_LOGIC;
      S_AXI_3_AWREADY : OUT STD_LOGIC
    );
  END COMPONENT kth_axi_Mesh_2D_Nostrum_2x2x1;
  ATTRIBUTE X_CORE_INFO : STRING;
  ATTRIBUTE X_CORE_INFO OF BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0_arch: ARCHITECTURE IS "kth_axi_Mesh_2D_Nostrum_2x2x1,Vivado 2016.3";
  ATTRIBUTE CHECK_LICENSE_TYPE : STRING;
  ATTRIBUTE CHECK_LICENSE_TYPE OF BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0_arch : ARCHITECTURE IS "BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0,kth_axi_Mesh_2D_Nostrum_2x2x1,{}";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ACLK: SIGNAL IS "xilinx.com:signal:clock:1.0 S_AXI_0_ACLK CLK";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ARESETN: SIGNAL IS "xilinx.com:signal:reset:1.0 S_AXI_0_ARESETN RST";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_0_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_0 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ACLK: SIGNAL IS "xilinx.com:signal:clock:1.0 S_AXI_1_ACLK CLK";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ARESETN: SIGNAL IS "xilinx.com:signal:reset:1.0 S_AXI_1_ARESETN RST";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_1_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_1 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ACLK: SIGNAL IS "xilinx.com:signal:clock:1.0 S_AXI_2_ACLK CLK";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ARESETN: SIGNAL IS "xilinx.com:signal:reset:1.0 S_AXI_2_ARESETN RST";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_2_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_2 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ACLK: SIGNAL IS "xilinx.com:signal:clock:1.0 S_AXI_3_ACLK CLK";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ARESETN: SIGNAL IS "xilinx.com:signal:reset:1.0 S_AXI_3_ARESETN RST";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S_AXI_3_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 S_AXI_3 AWREADY";
BEGIN
  U0 : kth_axi_Mesh_2D_Nostrum_2x2x1
    GENERIC MAP (
      C_S00_AXI_BASEADDR => 1879179264,
      C_S00_AXI_HIGHADDR => 1879310335,
      C_S01_AXI_BASEADDR => 1879179264,
      C_S01_AXI_HIGHADDR => 1879310335,
      C_S02_AXI_BASEADDR => 1879179264,
      C_S02_AXI_HIGHADDR => 1879310335,
      C_S03_AXI_BASEADDR => 1879179264,
      C_S03_AXI_HIGHADDR => 1879310335
    )
    PORT MAP (
      NoC_Irq_0 => NoC_Irq_0,
      S_AXI_0_ACLK => S_AXI_0_ACLK,
      S_AXI_0_ARESETN => S_AXI_0_ARESETN,
      S_AXI_0_AWADDR => S_AXI_0_AWADDR,
      S_AXI_0_AWVALID => S_AXI_0_AWVALID,
      S_AXI_0_AWPROT => S_AXI_0_AWPROT,
      S_AXI_0_WDATA => S_AXI_0_WDATA,
      S_AXI_0_WSTRB => S_AXI_0_WSTRB,
      S_AXI_0_WVALID => S_AXI_0_WVALID,
      S_AXI_0_BREADY => S_AXI_0_BREADY,
      S_AXI_0_ARADDR => S_AXI_0_ARADDR,
      S_AXI_0_ARPROT => S_AXI_0_ARPROT,
      S_AXI_0_ARVALID => S_AXI_0_ARVALID,
      S_AXI_0_RREADY => S_AXI_0_RREADY,
      S_AXI_0_ARREADY => S_AXI_0_ARREADY,
      S_AXI_0_RDATA => S_AXI_0_RDATA,
      S_AXI_0_RRESP => S_AXI_0_RRESP,
      S_AXI_0_RVALID => S_AXI_0_RVALID,
      S_AXI_0_WREADY => S_AXI_0_WREADY,
      S_AXI_0_BRESP => S_AXI_0_BRESP,
      S_AXI_0_BVALID => S_AXI_0_BVALID,
      S_AXI_0_AWREADY => S_AXI_0_AWREADY,
      NoC_Irq_1 => NoC_Irq_1,
      S_AXI_1_ACLK => S_AXI_1_ACLK,
      S_AXI_1_ARESETN => S_AXI_1_ARESETN,
      S_AXI_1_AWADDR => S_AXI_1_AWADDR,
      S_AXI_1_AWVALID => S_AXI_1_AWVALID,
      S_AXI_1_AWPROT => S_AXI_1_AWPROT,
      S_AXI_1_WDATA => S_AXI_1_WDATA,
      S_AXI_1_WSTRB => S_AXI_1_WSTRB,
      S_AXI_1_WVALID => S_AXI_1_WVALID,
      S_AXI_1_BREADY => S_AXI_1_BREADY,
      S_AXI_1_ARADDR => S_AXI_1_ARADDR,
      S_AXI_1_ARPROT => S_AXI_1_ARPROT,
      S_AXI_1_ARVALID => S_AXI_1_ARVALID,
      S_AXI_1_RREADY => S_AXI_1_RREADY,
      S_AXI_1_ARREADY => S_AXI_1_ARREADY,
      S_AXI_1_RDATA => S_AXI_1_RDATA,
      S_AXI_1_RRESP => S_AXI_1_RRESP,
      S_AXI_1_RVALID => S_AXI_1_RVALID,
      S_AXI_1_WREADY => S_AXI_1_WREADY,
      S_AXI_1_BRESP => S_AXI_1_BRESP,
      S_AXI_1_BVALID => S_AXI_1_BVALID,
      S_AXI_1_AWREADY => S_AXI_1_AWREADY,
      NoC_Irq_2 => NoC_Irq_2,
      S_AXI_2_ACLK => S_AXI_2_ACLK,
      S_AXI_2_ARESETN => S_AXI_2_ARESETN,
      S_AXI_2_AWADDR => S_AXI_2_AWADDR,
      S_AXI_2_AWVALID => S_AXI_2_AWVALID,
      S_AXI_2_AWPROT => S_AXI_2_AWPROT,
      S_AXI_2_WDATA => S_AXI_2_WDATA,
      S_AXI_2_WSTRB => S_AXI_2_WSTRB,
      S_AXI_2_WVALID => S_AXI_2_WVALID,
      S_AXI_2_BREADY => S_AXI_2_BREADY,
      S_AXI_2_ARADDR => S_AXI_2_ARADDR,
      S_AXI_2_ARPROT => S_AXI_2_ARPROT,
      S_AXI_2_ARVALID => S_AXI_2_ARVALID,
      S_AXI_2_RREADY => S_AXI_2_RREADY,
      S_AXI_2_ARREADY => S_AXI_2_ARREADY,
      S_AXI_2_RDATA => S_AXI_2_RDATA,
      S_AXI_2_RRESP => S_AXI_2_RRESP,
      S_AXI_2_RVALID => S_AXI_2_RVALID,
      S_AXI_2_WREADY => S_AXI_2_WREADY,
      S_AXI_2_BRESP => S_AXI_2_BRESP,
      S_AXI_2_BVALID => S_AXI_2_BVALID,
      S_AXI_2_AWREADY => S_AXI_2_AWREADY,
      NoC_Irq_3 => NoC_Irq_3,
      S_AXI_3_ACLK => S_AXI_3_ACLK,
      S_AXI_3_ARESETN => S_AXI_3_ARESETN,
      S_AXI_3_AWADDR => S_AXI_3_AWADDR,
      S_AXI_3_AWVALID => S_AXI_3_AWVALID,
      S_AXI_3_AWPROT => S_AXI_3_AWPROT,
      S_AXI_3_WDATA => S_AXI_3_WDATA,
      S_AXI_3_WSTRB => S_AXI_3_WSTRB,
      S_AXI_3_WVALID => S_AXI_3_WVALID,
      S_AXI_3_BREADY => S_AXI_3_BREADY,
      S_AXI_3_ARADDR => S_AXI_3_ARADDR,
      S_AXI_3_ARPROT => S_AXI_3_ARPROT,
      S_AXI_3_ARVALID => S_AXI_3_ARVALID,
      S_AXI_3_RREADY => S_AXI_3_RREADY,
      S_AXI_3_ARREADY => S_AXI_3_ARREADY,
      S_AXI_3_RDATA => S_AXI_3_RDATA,
      S_AXI_3_RRESP => S_AXI_3_RRESP,
      S_AXI_3_RVALID => S_AXI_3_RVALID,
      S_AXI_3_WREADY => S_AXI_3_WREADY,
      S_AXI_3_BRESP => S_AXI_3_BRESP,
      S_AXI_3_BVALID => S_AXI_3_BVALID,
      S_AXI_3_AWREADY => S_AXI_3_AWREADY
    );
END BD_kth_axi_Mesh_2D_Nostrum_2x2x1_0_0_arch;
