# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4.xci
# IP: The module: 'BD_dlmb_v10_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_dlmb_v10_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_dlmb_v10_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4.xci
# IP: The module: 'BD_dlmb_v10_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_dlmb_v10_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_dlmb_v10_4/BD_dlmb_v10_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_dlmb_v10_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
