# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_axi_crossbar_0_0/BD_axi_crossbar_0_0.xci
# IP: The module: 'BD_axi_crossbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_axi_crossbar_0_0/BD_axi_crossbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_crossbar_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_axi_crossbar_0_0/BD_axi_crossbar_0_0.xci
# IP: The module: 'BD_axi_crossbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tage/DegreeProject/zc702/NoC2xD/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage/NoC2x2_1MHz_ZeroReleaseSiegenDemo_Tage.srcs/sources_1/bd/BD/ip/BD_axi_crossbar_0_0/BD_axi_crossbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_crossbar_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
